### ISSUE TITLE
Tutorial-Links dead

### ISSUE THREAD

**Issue by Bizarrus** [Jjagg/MonoGame#8]
https://github.com/Jjagg/MonoGame/blob/docs-fresh/Documentation/tutorials/external.md/#L1

Links are dead

**Comment by Jjagg** [comment]
Hey, we've migrated the official documentation to docfx. Tutorials page is here: https://docs.monogame.net/articles/tutorials.html.

**Comment by Bizarrus** [comment]
But why, you dont delete the old resources? Ghost-Sites are bad for newcomer.

**Comment by Jjagg** [comment]
Good point, I will take it down. How did you find the page?
EDIT: Wait, I thought this was about my early docfx website I still had up, but this is just my fork of MonoGame...

**Comment by Bizarrus** [comment]
Uhm. Directly from GitHub on the Documentation.
